/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.control_estacionamiento.bean.Ubicacion;
import org.control_estacionamiento.controlador.ControladorUbicacion;

/**
 *
 * @author dafuentes
 */
public class Inicio extends javax.swing.JFrame {
    
    private final static int button_width   =   200;        // button width
    private final static int button_height  =   140;        // button height
    private final static int horizontalGap  =   10;         // horizontal gap in button
    private final static int verticalGap    =   10;         // verticle gap in button
    private final static int numberOfColumns=   4;          // number of colums in the button panel
    private final static int fontSize       =   11;         // font size of button name
    private final static int fontType       =   Font.BOLD;  // font type
    private final static String fontName    =   "Thoma";    // font name
    private final static Color  fontColor   =   new Color(0, 51, 255);  // font colot
    ControladorUbicacion controlador = new ControladorUbicacion().getInstance();

    /**
     * Creates new form NewJFrame
     */
    public Inicio() {
        initComponents();
        System.out.println(this.getClass());
        //Image image = new ImageIcon(this.getClass().getResource("carl.png")).getImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 100));

        pnl_menu.setPreferredSize(new java.awt.Dimension(965, 500));
        pnl_menu.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(757, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
         iniciar();
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    
    public void iniciar() {
        pnl_menu.removeAll();
        repaint();
        ControladorUbicacion controlador = new ControladorUbicacion().getInstance();
        JButton[] buttons = new JButton[controlador.getListado().size()];
        int i = 0;
        for(Ubicacion test: controlador.getListado() ) {
            buttons[i]  = new JButton(test.getDescripcion() +" - DISPONIBLE: " + test.getCantidadDisponible());
            buttons[i].setVerticalTextPosition(AbstractButton.BOTTOM);
            buttons[i].setHorizontalTextPosition(AbstractButton.CENTER);

            buttons[i].setBorder(javax.swing.BorderFactory.createEtchedBorder());
            buttons[i].setFont(new java.awt.Font("Tahoma", 1, 13));
            buttons[i].setForeground(new java.awt.Color(0, 51, 255));

            buttons[i].setActionCommand(test.getId() + "");
            buttons[i].addActionListener(new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                   String choice = e.getActionCommand();
                   verEspacio(choice);
                }
            });       
            pnl_menu.add(buttons[i]);
            i++;
        }
        pnl_menu.revalidate();
        pnl_menu.repaint();
        //pack();
    }
    
    public void verEspacio(String id) {
        this.pnl_menu.removeAll();
        repaint();
        Ubicacion ubicacion = controlador.buscarUbicacion(Integer.parseInt(id));
        ParqueoFrame parqueo = new ParqueoFrame();
        //System.out.println(ubicacion.getDescripcion());
        this.pnl_menu.add(parqueo.obtenerPosiciones(ubicacion, this)); 
        this.pnl_menu.setSize(1000,500);
        this.pnl_menu.revalidate();
        this.pnl_menu.repaint();
    };
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_menu;
    // End of variables declaration//GEN-END:variables
}
