/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.control_estacionamiento.bean.Parqueo;
import org.control_estacionamiento.bean.Tarifa;
import org.control_estacionamiento.bean.Ticket;
import org.control_estacionamiento.controlador.ControladorParqueo;
import org.control_estacionamiento.controlador.ControladorTicket;

/**
 *
 * @author dafuentes
 */
public class VentanaEntrada extends javax.swing.JDialog {

    protected SimpleDateFormat timeFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
    private Parqueo parqueo_disponible;
    private Date currentTime;
    DateFormat datehora = new SimpleDateFormat("HH");
    DateFormat dateFormat = new SimpleDateFormat("aa");
    Date date = new Date();
    /**
     * Creates new form VentanaEntrada
     */
    public VentanaEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_placa = new javax.swing.JLabel();
        lbl_entrada = new javax.swing.JLabel();
        lbl_tarifa = new javax.swing.JLabel();
        lbl_parqueo = new javax.swing.JLabel();
        txt_placa = new javax.swing.JFormattedTextField();
        txt_parqueo = new javax.swing.JFormattedTextField();
        txt_entrada = new javax.swing.JFormattedTextField();
        txt_tarifa = new javax.swing.JFormattedTextField();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelSave = new javax.swing.JLabel();
        jLabelCancel = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 471));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_placa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_placa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_placa.setText("PLACA");
        getContentPane().add(lbl_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 129, -1));

        lbl_entrada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_entrada.setForeground(new java.awt.Color(255, 255, 255));
        lbl_entrada.setText("FECHA Y HORA");
        getContentPane().add(lbl_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 129, -1));

        lbl_tarifa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_tarifa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarifa.setText("TARIFA");
        getContentPane().add(lbl_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 129, -1));

        lbl_parqueo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_parqueo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_parqueo.setText("PARQUEO ASIGNADO");
        getContentPane().add(lbl_parqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 150, -1));

        txt_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, -1));

        txt_parqueo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_parqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, -1));

        txt_entrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_entradaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, -1));

        txt_tarifa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 120, -1));

        btn_guardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save.png"))); // NOI18N
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setFocusPainted(false);
        btn_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save-preseed.png"))); // NOI18N
        btn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save-preseed.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 70, -1));

        btn_cancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel.png"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setFocusPainted(false);
        btn_cancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel-pressed.png"))); // NOI18N
        btn_cancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel-pressed.png"))); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 70, -1));

        jButtonRegresar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow (2).png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setFocusPainted(false);
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabelSave.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelSave.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSave.setText("Guardar");
        getContentPane().add(jLabelSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 70, -1));

        jLabelCancel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelCancel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancel.setText("Cancelar");
        getContentPane().add(jLabelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 70, -1));

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("NUEVA ENTRADA");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/qPexDF.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_entradaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        try {
            BufferedWriter rep = new BufferedWriter(new FileWriter("reporte.txt", true));

            if (parqueo_disponible != null) {
                ControladorTicket ctl_ticket = new ControladorTicket().getInstance();
                Ticket ticket = new Ticket();
                ticket.setId(ctl_ticket.getListadoTicket().size() + 1);
                ticket.setHoraEntrada(currentTime);
                ticket.setPlaca(txt_placa.getText());
                ticket.setParqueo(parqueo_disponible);
                ticket.setTarifa(Tarifa.getTarifa());
                parqueo_disponible.setDisponible(false);
                ctl_ticket.agregarTicket(ticket);

                rep.write(datehora.format(date) + ",");
                rep.write(dateFormat.format(date) + ",");
                rep.write(txt_placa.getText());
                rep.newLine();
                rep.close();
                
            }
            this.dispose();
            VentanaPrincipal regreso = new VentanaPrincipal();
            regreso.setVisible(true);
            this.setVisible(false);
        } catch (IOException e) {
            System.out.println("ERROR");
        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal regreso = new VentanaPrincipal();
        regreso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal cancelar = new VentanaPrincipal();
        cancelar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   VentanaEntrada dialog = new VentanaEntrada(new javax.swing.JFrame(), true);
                //   dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                //       @Override
                //       public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
                //       }
                //   });
                //   dialog.setVisible(true);
            }
        });
    }

    public void agregarComponente() {
        this.setLocationRelativeTo(null);

        // HORA ENTRADA
        Calendar currentCalendar = Calendar.getInstance();
        currentTime = currentCalendar.getTime();
        txt_entrada.setValue(timeFormat.format(currentTime));
        txt_entrada.setEditable(false);

        // TARIFA
        txt_tarifa.setValue(Tarifa.getTarifa());
        txt_tarifa.setEditable(false);

        // PARQUEO
        ControladorParqueo ctl_parqueo = new ControladorParqueo().getInstance();
        parqueo_disponible = ctl_parqueo.getParqueoDisponible();

        btn_guardar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                btnGuardarActionPerformed(e);
            }
        });

        if (parqueo_disponible != null) {
            txt_parqueo.setValue(parqueo_disponible.getDescripcion() + " - " + parqueo_disponible.getUbicacion().getDescripcion());
        } else {
            btn_guardar.setEnabled(false);
            txt_parqueo.setValue("No hay parqueos");
        }
        txt_parqueo.setEditable(false);

        btn_cancelar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                btnCancelarActionPerformed(e);
            }
        });
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelCancel;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSave;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel lbl_entrada;
    private javax.swing.JLabel lbl_parqueo;
    private javax.swing.JLabel lbl_placa;
    private javax.swing.JLabel lbl_tarifa;
    private javax.swing.JFormattedTextField txt_entrada;
    private javax.swing.JFormattedTextField txt_parqueo;
    private javax.swing.JFormattedTextField txt_placa;
    private javax.swing.JFormattedTextField txt_tarifa;
    // End of variables declaration//GEN-END:variables
}
