/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author dafuentes
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_menu.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        JButton btn_ingreso = new JButton("Nuevo Ingreso");	
        btn_ingreso.setPreferredSize(new Dimension(40, 40));
        btn_ingreso.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnEntradaActionPerformed(e);
            }
        });   
        JButton btn_salida = new JButton("Nueva Salida");
	btn_salida.setPreferredSize(new Dimension(40, 40));
        btn_salida.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnSalidaActionPerformed(e);
            }
        });
        JButton btn_reporte = new JButton("Reporte");		
	btn_reporte.setPreferredSize(new Dimension(40, 40));
        btn_reporte.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnReporteActionPerformed(e);
            }
        });   
        JButton btn_parqueo = new JButton("Ver Parqueos");
	btn_parqueo.setPreferredSize(new Dimension(40, 40));
        JButton btn_tarifa = new JButton("Tarifa");
	btn_tarifa.setPreferredSize(new Dimension(40, 40));
        btn_tarifa.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnTarifaActionPerformed(e);
            }
        });   
        pnl_menu.add(btn_ingreso);
	pnl_menu.add(btn_salida);
	pnl_menu.add(btn_reporte);
	pnl_menu.add(btn_parqueo);
        pnl_menu.add(btn_tarifa);
    }
    
    private void btnEntradaActionPerformed(ActionEvent evt) {
        VentanaEntrada ventanaEntrada = new VentanaEntrada(this, true);
        ventanaEntrada.agregarComponente();
    }
    
    private void btnSalidaActionPerformed(ActionEvent evt) {
        VentanaSalida ventanaSalida = new VentanaSalida(this, true);
        ventanaSalida.agregarComponente();
    }
    
    private void btnTarifaActionPerformed(ActionEvent evt) {
        VentanaTarifa ventanaTarifa = new VentanaTarifa(this, true);
    }
    
    private void btnReporteActionPerformed(ActionEvent evt) {
        VentanaReporte ventanaReporte = new VentanaReporte(this, true);
        ventanaReporte.agregarComponente();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_menu;
    // End of variables declaration//GEN-END:variables
}
