/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import org.control_estacionamiento.bean.Parqueo;
import org.control_estacionamiento.bean.Tarifa;
import org.control_estacionamiento.bean.Ticket;
import org.control_estacionamiento.controlador.ControladorParqueo;
import org.control_estacionamiento.controlador.ControladorTicket;

/**
 *
 * @author dafuentes
 */
public class VentanaSalida extends javax.swing.JDialog {
    
    protected SimpleDateFormat timeFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
    private ControladorTicket ctl_ticket = new ControladorTicket().getInstance();
    private Parqueo parqueo_disponible;
    private Date currentTime;
    
//    private JFormattedTextField txt_entrada;
//    private JFormattedTextField txt_salida;
//    private JFormattedTextField txt_placa;
//    private JFormattedTextField txt_tarifa;
//    private JFormattedTextField txt_total;
//    private JFormattedTextField txt_parqueo;
//    private JButton btn_guardar;
    
    /**
     * Creates new form VentanaSalida
     */
    public VentanaSalida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_guardar = new javax.swing.JButton();
        txt_salida = new javax.swing.JFormattedTextField();
        txt_entrada = new javax.swing.JFormattedTextField();
        txt_placa = new javax.swing.JFormattedTextField();
        txt_tarifa = new javax.swing.JFormattedTextField();
        txt_total = new javax.swing.JFormattedTextField();
        txt_parqueo = new javax.swing.JFormattedTextField();
        lbl_salida = new javax.swing.JLabel();
        lbl_entrada = new javax.swing.JLabel();
        lbl_tarifa = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_parqueo = new javax.swing.JLabel();
        lbl_buscar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabelGuardar = new javax.swing.JLabel();
        jLabelCancelar = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("img/parking(1).png")).getImage());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 471));
        setResizable(false);
        setSize(new java.awt.Dimension(540, 471));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save.png"))); // NOI18N
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setFocusPainted(false);
        btn_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save-preseed.png"))); // NOI18N
        btn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/save-preseed.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 70, -1));

        txt_salida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));

        txt_entrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_entradaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, -1));

        txt_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));

        txt_tarifa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));

        txt_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, -1));

        txt_parqueo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_parqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, -1));

        lbl_salida.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_salida.setForeground(new java.awt.Color(255, 255, 255));
        lbl_salida.setText("HORA DE SALIDA");
        getContentPane().add(lbl_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, -1));

        lbl_entrada.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_entrada.setForeground(new java.awt.Color(255, 255, 255));
        lbl_entrada.setText("HORA DE ENTRADA");
        getContentPane().add(lbl_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, -1));

        lbl_tarifa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_tarifa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tarifa.setText("TARIFA");
        getContentPane().add(lbl_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 140, -1));

        lbl_total.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total.setText("TOTAL");
        getContentPane().add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        lbl_parqueo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_parqueo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_parqueo.setText("PARQUEO");
        getContentPane().add(lbl_parqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 140, -1));

        lbl_buscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buscar.setText("BUSCAR PLACA");
        getContentPane().add(lbl_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 140, -1));

        btn_buscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/search.png"))); // NOI18N
        btn_buscar.setBorderPainted(false);
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.setFocusPainted(false);
        btn_buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/search-pressed.png"))); // NOI18N
        btn_buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/search-pressed.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, -1));

        btn_cancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel.png"))); // NOI18N
        btn_cancelar.setBorderPainted(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setFocusPainted(false);
        btn_cancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel-pressed.png"))); // NOI18N
        btn_cancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/cancel-pressed.png"))); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 70, -1));

        jButtonRegresar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow (2).png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setFocusPainted(false);
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabelGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGuardar.setText("Guardar");
        getContentPane().add(jLabelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 70, -1));

        jLabelCancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabelCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCancelar.setText("Cancelar");
        getContentPane().add(jLabelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 70, -1));

        jLabelTitle.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("NUEVA SALIDA");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/qPexDF.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_entradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_entradaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal cancelar = new VentanaPrincipal();
        cancelar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal regresar = new VentanaPrincipal();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              /*  VentanaSalida dialog = new VentanaSalida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {*/
                        System.exit(0);
                  /*  }
                });
                dialog.setVisible(true);*/
            }
        });
    }
    
    public void agregarComponente() {
        this.setLocationRelativeTo(null);
        
        
        // PLACA
        
        // BOTON BUSCAR
        btn_buscar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnBuscarActionPerformed(e);
            }
        }); 

        // HORA ENTRADA
        Calendar currentCalendar = Calendar.getInstance();
        currentTime = currentCalendar.getTime();
        //txt_entrada.setValue(timeFormat.format(currentTime));
        txt_entrada.setEditable(false);
        
        // HORA SALIDA
        txt_salida.setValue(timeFormat.format(currentTime));
        txt_salida.setEditable(false);
        
        // TARIFA
        //txt_tarifa.setValue(Tarifa.getTarifa());
        txt_tarifa.setEditable(false);
        
        // TOTAL
        //txt_total.setValue(Tarifa.getTarifa());
        txt_total.setEditable(false);
        
        // PARQUEO
        ControladorParqueo ctl_parqueo = new ControladorParqueo().getInstance();
        btn_guardar.setEnabled(false);
        btn_guardar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnGuardarActionPerformed(e);
            }
        }); 
        txt_parqueo.setEditable(false);
        
        
        btn_cancelar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnCancelarActionPerformed(e);
            }
        });   
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
    
    private void btnBuscarActionPerformed(ActionEvent evt) {
        Ticket ticket = ctl_ticket.getTicket(txt_placa.getText());
        if (ticket != null) {
            btn_guardar.setEnabled(true);
            txt_entrada.setValue(timeFormat.format(ticket.getHoraEntrada()));
            txt_parqueo.setValue(ticket.getParqueo().getUbicacion().getDescripcion() + " - " + ticket.getParqueo().getDescripcion());
            txt_tarifa.setValue(ticket.getTarifa());
            long inicial = ticket.getHoraEntrada().getTime();
            long fin = currentTime.getTime();
            parqueo_disponible = ticket.getParqueo();
            long resta= fin - inicial;
            resta=resta /(1000*60);
            double tarifa = 0;
            if (Tarifa.getTiempo() <= resta) {
                tarifa = ticket.getTarifa() * resta;
            } 
            txt_total.setValue(tarifa);
        } else {
            txt_entrada.setValue("");
            txt_parqueo.setValue("");
            txt_tarifa.setValue(0);
            txt_total.setValue(0);
            parqueo_disponible = null;
            btn_guardar.setEnabled(false);
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        if (parqueo_disponible != null) {
            Ticket ticket = ctl_ticket.getTicket(txt_placa.getText());
            if (ticket != null) {
                ticket.setHoraSalida(currentTime);
                ticket.setPagado(true);
                ticket.setTotal(Double.parseDouble(txt_total.getText()));
                parqueo_disponible.setDisponible(true);
            }
        }
        
        VentanaPrincipal regresar = new VentanaPrincipal();
        regresar.setVisible(true);
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelCancelar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_entrada;
    private javax.swing.JLabel lbl_parqueo;
    private javax.swing.JLabel lbl_salida;
    private javax.swing.JLabel lbl_tarifa;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JFormattedTextField txt_entrada;
    private javax.swing.JFormattedTextField txt_parqueo;
    private javax.swing.JFormattedTextField txt_placa;
    private javax.swing.JFormattedTextField txt_salida;
    private javax.swing.JFormattedTextField txt_tarifa;
    private javax.swing.JFormattedTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
