/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import org.control_estacionamiento.bean.Parqueo;
import org.control_estacionamiento.bean.Tarifa;
import org.control_estacionamiento.bean.Ticket;
import org.control_estacionamiento.controlador.ControladorParqueo;
import org.control_estacionamiento.controlador.ControladorTicket;

/**
 *
 * @author dafuentes
 */
public class VentanaEntrada extends javax.swing.JDialog {
    
    protected SimpleDateFormat timeFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm aa");
    private JFormattedTextField txt_entrada;
    private JFormattedTextField txt_placa;
    private Parqueo parqueo_disponible;
    private Date currentTime;
    /**
     * Creates new form VentanaEntrada
     */
    public VentanaEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        agregarComponente();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JPanel();
        pnl_accion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnl_menu.setLayout(new java.awt.GridLayout(5, 2, 10, 5));

        pnl_accion.setLayout(new java.awt.GridLayout(1, 0, 2, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_accion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(pnl_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaEntrada dialog = new VentanaEntrada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setSize(425, 335);
        
        // PLACA
        JLabel lbl_placa = new JLabel("PLACA",SwingConstants.CENTER);
        txt_placa = new JFormattedTextField();
        pnl_menu.add(lbl_placa);
        pnl_menu.add(txt_placa);
        
        // HORA ENTRADA
        JLabel lbl_entrada = new JLabel("FECHA Y HORA",SwingConstants.CENTER);
        txt_entrada = new JFormattedTextField();
        Calendar currentCalendar = Calendar.getInstance();
        currentTime = currentCalendar.getTime();
        txt_entrada.setValue(timeFormat.format(currentTime));
        txt_entrada.setEditable(false);
        pnl_menu.add(lbl_entrada);
        pnl_menu.add(txt_entrada);
        
        // TARIFA
        JLabel lbl_tarifa = new JLabel("TARIFA",SwingConstants.CENTER);
        JFormattedTextField txt_tarifa = new JFormattedTextField();
        txt_tarifa.setValue(Tarifa.getTarifa());
        txt_tarifa.setEditable(false);
        
        pnl_menu.add(lbl_tarifa);
        pnl_menu.add(txt_tarifa);
        
        // PARQUEO
        JLabel lbl_parqueo = new JLabel("PARQUEO ASIGNADO",SwingConstants.CENTER);
        
        ControladorParqueo ctl_parqueo = new ControladorParqueo().getInstance();
        parqueo_disponible = ctl_parqueo.getParqueoDisponible();
        JFormattedTextField txt_parqueo = new JFormattedTextField();
        JButton btn_guardar = new JButton("Guardar");
        btn_guardar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnGuardarActionPerformed(e);
            }
        }); 
        
        if (parqueo_disponible != null) {
            txt_parqueo.setValue(parqueo_disponible.getDescripcion() + " - " + parqueo_disponible.getUbicacion().getDescripcion());
        } else {
            btn_guardar.setEnabled(false);
            txt_parqueo.setValue("No hay parqueos");
        }
        txt_parqueo.setEditable(false);
        pnl_menu.add(lbl_parqueo);
        pnl_menu.add(txt_parqueo);
        
        
        JButton btn_cancelar = new JButton("Cancelar");
        btn_cancelar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               btnCancelarActionPerformed(e);
            }
        });   
        pnl_accion.add(btn_guardar);
        pnl_accion.add(btn_cancelar);
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        if (parqueo_disponible != null) {
            ControladorTicket ctl_ticket = new ControladorTicket().getInstance();
            Ticket ticket = new Ticket();
            ticket.setId(ctl_ticket.getListadoTicket().size() + 1);
            ticket.setHoraEntrada(currentTime);
            ticket.setPlaca(txt_placa.getText());
            ticket.setParqueo(parqueo_disponible);
            ticket.setTarifa(Tarifa.getTarifa());
            parqueo_disponible.setDisponible(false);
            ctl_ticket.agregarTicket(ticket);
        }
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_accion;
    private javax.swing.JPanel pnl_menu;
    // End of variables declaration//GEN-END:variables
}
