/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.control_estacionamiento.frame;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dafuentes
 */
public class VentanaReporteHora extends javax.swing.JDialog {
    /**
     * Creates new form VentanaReporte
     */
    public VentanaReporteHora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("img/parking(1).png")).getImage());
        this.setLocationRelativeTo(null);
        agregarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_menu = new javax.swing.JScrollPane();
        tbl_horas = new javax.swing.JTable();
        jButtonRegresar = new javax.swing.JButton();
        jLabelReporte = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("img/parking(1).png")).getImage());
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(540, 471));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_horas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 51)));
        tbl_horas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbl_horas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "HORA", "CANTIDAD DE AUTOS"
            }
        ));
        tbl_horas.setGridColor(new java.awt.Color(255, 153, 0));
        tbl_horas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        pnl_menu.setViewportView(tbl_horas);
        if (tbl_horas.getColumnModel().getColumnCount() > 0) {
            tbl_horas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_horas.getColumnModel().getColumn(1).setPreferredWidth(60);
            tbl_horas.getColumnModel().getColumn(2).setPreferredWidth(130);
        }

        getContentPane().add(pnl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 480, 275));

        jButtonRegresar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow (2).png"))); // NOI18N
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setBorderPainted(false);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setFocusPainted(false);
        jButtonRegresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/go-back-arrow.png"))); // NOI18N
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelReporte.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabelReporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReporte.setText("REPORTE DE HORAS");
        getContentPane().add(jLabelReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/control_estacionamiento/frame/img/qPexDF.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal regresar = new VentanaPrincipal();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            /*    VentanaReporte dialog = new VentanaReporte(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {*/
                        System.exit(0);
             //      }
             //   });
             //  dialog.setVisible(true);
            }
        });
    }
    
    public void agregarComponente() {
        this.setLocationRelativeTo(null);
        
        try {
            String linea;
            String horas[] = {"01","02","03","04","05","06","07","08","09","10","11","12",
                                "13","14","15","16","17","18","19","20","21","22","23","24"};
            String [] campos;
            String hora = "";
            String form = "";
            int count = 0;
            int id = 1;
            BufferedReader entrada = new BufferedReader(new FileReader("reporte.txt"));
            try {

                for (int x = 0; x < horas.length - 1; x++) {
                    hora = horas[x];
                    while ((linea = entrada.readLine()) != null) {
                        campos = linea.split(",");
                        
                        if (campos[0].equals(hora)) {
                            form = campos[1];
                            count++;
                        }
                    }
                    
                    if (count != 0){
                        DefaultTableModel model = (DefaultTableModel) tbl_horas.getModel();
                        Object rowData[] = {id++ ,horas[x] + " " + form, count};
                        model.addRow(rowData);
                    }
                    entrada = new BufferedReader(new FileReader("reporte.txt"));
                    count = 0;
                    form = "";
                }

            } catch (EOFException e) {
            }
            entrada.close();
        } catch (IOException e) {
            System.out.println("ERROR");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelReporte;
    private javax.swing.JScrollPane pnl_menu;
    private javax.swing.JTable tbl_horas;
    // End of variables declaration//GEN-END:variables
}
